In [1]:
from __future__ import unicode_literals, division

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
ses = tf.Session()

In [8]:
a = tf.constant(np.random.random((20,100)))

In [9]:
b = tf.constant(np.random.random((20,100)))

In [16]:
n = tf.norm(a-b, 'euclidean', axis = -1)

In [19]:
ses.run(n)

array([3.98217617, 4.26706675, 4.09455072, 3.82226862, 4.25820628,
       3.82370704, 4.18923608, 3.84230054, 4.05102787, 3.8155245 ,
       4.35476129, 4.20256117, 3.97920503, 3.99755646, 4.24608188,
       3.95935031, 4.13573671, 3.76400033, 4.17309381, 4.31803685])

In [21]:
np.random.random_integers(0,1,size=20)

/home/biswadip/.local/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 1 + 1) instead
  """Entry point for launching an IPython kernel.


array([0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1])

In [24]:
label = tf.constant(np.random.random_integers(0,1,size=20), dtype=tf.float64)

/home/biswadip/.local/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 1 + 1) instead
  """Entry point for launching an IPython kernel.


In [25]:
loss = label*n - (1- label)*n

In [29]:
ses.run(n)

array([3.98217617, 4.26706675, 4.09455072, 3.82226862, 4.25820628,
       3.82370704, 4.18923608, 3.84230054, 4.05102787, 3.8155245 ,
       4.35476129, 4.20256117, 3.97920503, 3.99755646, 4.24608188,
       3.95935031, 4.13573671, 3.76400033, 4.17309381, 4.31803685])